# Generated by Django 4.1.1 on 2022-11-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_user"),
    ]

    operations = [
        migrations.RenameField(model_name="todo", old_name="read", new_name="done",),
    ]
